### ISSUE TITLE
How to deal with a odd number of children?

### ISSUE THREAD

**Issue by borgeser** [tbelhalfaoui/deuxpots#9]
Hi Thomas, nice work! Just a question.

How can I do if I have an odd number of children for line 0CF and if I want to share equally the children between the 2 parents? Because the app does not accept "half-children".

Thanks.

**Comment by tbelhalfaoui** [comment]
Hi @borgeser,

Thanks for your message! Indeed, it is an important issue that you point out.

But in the current implementation, it is not easy to handle. Right now, I simulate each partner's income by simulating this person being single, and sending all their numbers (children, income, etc.) to the official tax simulator API. But the simulator API does not accept "half-children"...

So, an option I thought of would have been to make two simulations for one partner. For instance, for 0.5 children, make one simulation with no child, another one with one child, and take the average of the two tax amounts. But sadly, this does not work either, since the function that computes the tax is not linear, but piecewise linear (due to the progressive tax rate).

So the only way I could make it work would be to:
* Manually handle the computation of the number of people in the household ("nombre de parts"),
* Use the simulator only to get the total taxable revenue,
* Divide the taxable revenue by the number of people (potentially a float),
* Compute the tax amount myself, using the publicly available formula (piecewise linear function).

This is definitely doable, but would imply some checks to make sure I do the calculation right and I don't forget any corner case (and there are many!...). And also make sure I update the function that computes the tax amount when the rate change (potentially once a year).

That being said, I put this on my todo list, and I will try too look into it soon :)

**Comment by tbelhalfaoui** [comment]
Hi @borgeser!

I just implemented a way of handling this in https://github.com/tbelhalfaoui/deuxpots/pull/10.

Actually, it was too risky to re-implement the logic that handles children. It is really complex, with a lot of thresholds and exceptions.. (see [this page](https://www.impots.gouv.fr/sites/default/files/media/3_Documentation/depliants/nid_4001_gp_110.pdf)).

So the hacky way of doing it, which I implemented, is to move the "half-children" to the "alternating custody" box (i.e. each "0.5" in `0CF` and `0CG` box is silently moved to `0CH` and `0CI` respectively). I think it works well and it makes sense.

But of course, the downside is that it can only handle "0.5" increments (not 0.3, 0.25 or anything more fancy). Still, I hope it covers most of the needs, including yours. I would be happy to have your feedback if you have time to test it :)

**Comment by tbelhalfaoui** [comment]
@borgeser I just fixed (in https://github.com/tbelhalfaoui/deuxpots/commit/94551f92fd188ae65364ef456e7c5d8a355ff2a1) an issue with the child care cost boxes (`7GA`, `7GB` and `7GC`) that were broken in the case a child was "split" between the partners. I hope this time it works 🤞
